name: Ilk Deneme Workflowum

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  deneme:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: Celo
        - name: Hello Celo

          run: |
            ls -al
            echo "Hello Celo"
            printenv

        - name: Celo
          uses: mscoutermarsh/cowsays-action@master
          with:
            text: "Hello Celo Ne Yapıyorsun!"
            color: 'blue'
            

