name: Ilk Deneme Workflowum

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  deneme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: DurumYaz
      run: |
        echo "ilk deneme workflowum"
        printenv